Add samples for azure active directory b2c work with spring security
spring-projects/spring-security-samples pull request #31
Opened 2021-09-01 10:08 UTC by zhichengliu12581

We plan to [deprecate our B2C starter](https://github.com/Azure/azure-sdk-for-java/issues/23545) because the functions provided in our starter can already be implemented through spring security. So we hope to add some samples that implement b2c functions through spring security to this repo to show how azure active directory b2c works with spring security.
This pr only provides the simplest sample, these functions already have similar samples. However, we expect to provide these samples to describe how spring security and b2c work together. Perhaps these samples can better show users how B2C and spring security are used together.
![1630490512(1)](https://user-images.githubusercontent.com/70368631/131652450-e02c0512-8b4b-42c1-b71f-99a47986b69d.png)

2021-09-02 07:52 UTC, chenrujun requested changes

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/README.adoc
> += Azure Active Directory B2C with Spring Security Sample
Tutorial of using Azure Active Directory B2C by Spring Security

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/README.adoc
> +In the current folder, we have the these samples to introduce how to use the Azure Active Directory B2C functions through Spring Security.
By reading this tutorial, you will learn how to use Azure Active Directory B2C by Spring Security.

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/README.adoc
> += Azure Active Directory B2C with Spring Security Sample
Add toc in line 2:
```
:toc:
```
Refs: https://docs.asciidoctor.org/asciidoc/latest/toc/

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/README.adoc
> +* <<work-as-resource-server, Work as Resource Server>>
We can delete this after we have `:toc:`

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/README.adoc
> +[[create-azure-active-directory-B2C-resources]]
Before create resource, we should tell customer how to get a Azure account. I mean we need a `prerequisites`

Example:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/ENVIRONMENT_CHECKLIST.md#prerequisites

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/README.adoc
> +After prepare Azure Active Directory B2C resources, we can use this <<../azure-active-directory-b2c/web-application-1-simple-sample/, sample>> to use it as a web application.
Sample project: <<./web-application-1-simple-sample/, web-application-1-simple-sample>>

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/README.adoc
> +In order to jump to the correct page (home) after `profile-edit` and `password-reset`, we need to add `http://localhost:8080/` in the redirect uri.
This already exist in `Register your Azure Active Directory B2C application`

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/README.adoc
> +=== Application config
Fill necessary contents in sample project.

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/README.adoc
> +=== Application config
Fill necessary contents in sample project.

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/README.adoc
> +Launch the Spring Boot 2.0 sample and go to `http://localhost:8080`.
Lunch the sample project, then open `http://localhost:8080` by browser.

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/README.adoc
> +
Lunch the sample project. Then open `http://localhost:8080/getResourceServer` by browser. The browser will access `web-application-1-simple-sample`, and `web-application-1-simple-sample` will access `resource-server-1-simple-server` by access token.

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/resource-server-1-simple-sample/README.adoc
> +Please refer to this <<../README.adoc#work-as-resource-server,document>>
nit: `document` -> `tutorial`.

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/resource-server-1-simple-sample/src/main/java/com/spring/sample/b2c/controller/SampleController.java
> +        return "Hello, this is aad-b2c-resource-server-simple-sample.";
`this is a resource-server protected by Azure Active Directory B2C. ` Then we can reuse this if we adding other resource server projects.

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/web-application-1-simple-sample/README.adoc
> +Please refer to this <<../README.adoc#work-as-web-application,document>>
Same here.

2021-09-02 07:52 UTC, chenrujun commented on servlet/spring-boot/java/oauth2/azure-active-directory-b2c/web-application-1-simple-sample/src/main/java/com/spring/sample/b2c/controller/SampleController.java
> +    @GetMapping(value = { "/getResourceServer" })
`/getResourceServer` -> `/resourceServer`

Not use verb in url.

Refs: https://cloud.google.com/blog/products/api-management/restful-api-design-nouns-are-good-verbs-are-bad

2021-09-02 23:02 UTC, jzheaux commented
> This pr only provides the simplest sample, these functions already have similar samples.

This was my first thought as well when looking over the PR. I wonder if it would be better to first contribute to the READMEs.

For example, you could add to [the OAuth 2.0 Login setup instructions](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/oauth2/login#login-with-okta), [the WebClient instructions](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/oauth2/webclient#oauth-20-webclient-servlet-sample), etc.

2021-09-06 09:36 UTC, zhichengliu12581 commented
@jzheaux Thank you very much for your review.
I added the configuration description of B2C in [OAuth 2.0 Login Setting Instructions](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/oauth2/login).

As a resource server, I intend to use it as the simplest example of use. Because other examples will be added later, including the use of custom `JwtDecoder`, `DelegatingJwtGrantedAuthoritiesConverter`, etc., and how to configure it in B2C. It may take some time for users to configure these things in B2C, and some progressive samples may be convenient for users to understand how to configure.

The same is true as a client. Some functions (such as adding role or configuring logout) will be more convenient for users to configure if there is a sample to show.

If you agree, I will add more examples of how to use B2C. New features will be gradually added between them.

2021-09-17 08:53 UTC, zhichengliu12581 commented
@jzheaux Can you please help to review this pr again.
I added some samples, and there are some small differences between them.
Maybe by adding chapters, and each chapter contains a small change compare to previous chapter can make user easily understand the usage of each feature.
I may need to modify some descriptions, but please see if it is appropriate to add such samples.

2021-09-22 01:18 UTC, zhichengliu12581 commented
@jzheaux ping

2021-09-23 17:40 UTC, jzheaux commented
>  It may take some time for users to configure these things in B2C, and some progressive samples may be convenient for users to understand how to configure.

While I agree with this, I don't think `spring-security-samples` is the right home for it. You can imagine if each vendor wanted to add their own chapters of samples into `spring-security-samples` for any given module and see that it would quickly become unmaintainable.

Additionally, since Azure uses their own set of properties, I think this could end up being confusing to new users perusing this repository.

For now, I'd leave the PR at just adding README instructions that get things working with the Spring Boot default properties. If you have your own repo that points to additional samples, I think it would be reasonable to include a link to it in the README.

2022-03-17 12:40 UTC, marcusdacoregio commented
I'm closing this since there weren't any updates since @jzheaux last comment. We can always reopen it if the suggested changes are addressed.

Thanks!

2022-03-17 12:40 UTC, closed without merging